services:
    web:
        container_name: "my_gym_trainer_web"
        build: .
        ports:
            - "80:80"
            - "8080:8080"
            - "5173:5173"
            - "443:443"
        networks:
            my_gym_trainer_network:
                ipv4_address: 192.168.152.55
        volumes:
            - .:/var/www/html
        tty: true
        stdin_open: true
        depends_on:
            - database
        environment:
            - CHOKIDAR_USEPOLLING=true

    database:
        image: mariadb:10.2.25-bionic
        container_name: "my_gym_trainer_db"
        ports:
            - "3306:3306"
        networks:
            my_gym_trainer_network:
                ipv4_address: 192.168.152.51
        volumes:
            - ./.docker/mariadb/data:/var/lib/mariadb
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 123
        command: --default-authentication-plugin=mysql_native_password

networks:
    my_gym_trainer_network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.152.0/24
